config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'home/index'

  devise_for :users

  get 'dashboard/index'

  root 'welcome#index'

  resources :subscribers, :only => [:index, :new, :create]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) do |u|
  		u.permit(:first_name, :last_name, :course, :school, :email, :password, :password_confirmation)
  	end
  	devise_parameter_sanitizer.for(:account_update) do |u|
  		u.permit(:first_name, :last_name, :course, :school, :email, :username, :password, :password_confirmation, :current_password, :profile_photo)
  	end
  end

  def configure_devise_permitted_parameters
  	registration_params = [:first_name, :last_name, :course, :school, :email, :username, :password, :password_confirmation]

  	if params[:action] == 'update'
  		devise_parameter_sanitizer.for(:account_update) { 
  			|u |u.permit(:first_name, :last_name, :short_bio, :email, :username, :password, :password_confirmation, :current_password)
  			# |u| u.permit(registration_params << :current_password)
  		}
  	elsif params[:action] == 'create'
  		devise_parameter_sanitizer.for(:sign_up) { 
  			|u| u.permit(registration_params) 
  		}
  	end
  end

  def after_sign_in_path_for(resource) 
    # session["user_return_to"] || profile_index_url
    case resource
    when User then home_index_url
    when Admin then dashboard_index_url
    end
  end 

  def after_sign_out_path_for(resource_or_scope)
  	new_user_session_path
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_admin!

	def index
		@subscribers = Subscriber.all
		@users = User.all
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
	def index
	end
	
	def new
		@subscriber = Subscriber.new
	end

	def create
		@subscriber = Subscriber.new(subscriber_params)

		respond_to do |format|
			if @subscriber.save
				format.html { redirect_to root_url, notice: 'Thanks for signing up! We\'ll send you updates soon!' }
			else
				format.html { render :new }
			end
		end

	end

	private

	def subscriber_params
		params.require(:subscriber).permit(:email)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.haml
/ %h1 Users

/ %table
/   %tr
/     %th First name
/     %th Last name
/     %th Course
/     %th School
/     %th	Email
/     %th

/   - @users.each do |user|
/     %tr
/       %td= user.first_name
/       %td= user.last_name
/       %td= user.course
/       %td= user.school
/       %td= user.email

/ %br

.container
  %h1 Subscribers

  %table
    %tr
      %th 
      %th Email
      %th

    - @subscribers.each.with_index(1) do |subscriber,index|
      %tr
        %td= "#{index}."
        %td= subscriber.email

  %br

app/views/home/index.html.haml
%h1 
	= "Welcome, #{current_user.first_name.capitalize} #{current_user.last_name.capitalize}"

%blockquote
	= current_user.email

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title morayta.ph
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Pacifico'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Cookie'

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          - if request.env['PATH_INFO'] == "/"
            %a.navbar-brand{href: "/#header-section"} morayta.ph
          -else
            = link_to "morayta.ph","/#header-section", :method => :get, :class => "navbar-brand"

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if request.env['PATH_INFO'] == "/"
              %li
                %a{:href => "#header-section"} HOME
              / %li
              /   %a{:href => "#about-section"} ABOUT
              / %li
              /   %a{:href => "#price-section"} PRICING
              %li
                %a{:href => "#contact-section"} SUBSCRIBE
            
            - else
              %li= link_to "HOME", "/#header-section", :method => :get
              / %li= link_to "ABOUT", "/#about-section", :method => :get
              / %li= link_to "PRICING", "/#price-section", :method => :get
              %li= link_to "SUBSCRIBE", "/#contact-section", :method => :get          
            
            / - if user_signed_in?
            /   %li
            /     = link_to   "LOGOUT, #{current_user.last_name}", destroy_user_session_path ,  :method => :delete
            / - else
            /   - unless admin_signed_in?
            /     %li= link_to "LOGIN", new_user_session_path, :method => :get

            / - if admin_signed_in?
            /   %li
            /     = link_to   "LOGOUT, #{current_admin.last_name}", destroy_admin_session_path ,  :method => :delete

    .container.main
      - if notice
        .alert.alert-success.alert-dismissible{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %strong 
            = notice
      - if alert
        .alert.alert-danger.alert-dismissible{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %strong 
            = alert

    = yield

    .footer#footer
      .container
        %p.text-muted
          Copyright ©2014 Penya & Friends
  

app/views/layouts/applicationx.html.haml
!!!
%html
  %head
    %title pre-board
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} pr(e)-board
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              - if admin_signed_in?
                = link_to "Home", dashboard_index_url
              - elsif user_signed_in?
                = link_to "Home", "/"
              - else
                = link_to "Home", "#"
            - if user_signed_in?
              %li
                = link_to   "Logout, #{current_user.last_name}", destroy_user_session_path ,  :method => :delete
            - else
              - unless admin_signed_in?
                %li= link_to "Login", new_user_session_path, :method => :get

            - if admin_signed_in?
              %li
                = link_to   "Logout, #{current_admin.last_name}", destroy_admin_session_path ,  :method => :delete


    .container
      - if notice
        .alert.alert-success.alert-dismissible{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %strong 
            = notice
      - if alert
        .alert.alert-danger.alert-dismissible{:role => "alert"}
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %strong 
            = alert

      = yield

    .footer
      .container
        %p.text-muted
          Copyright ©2014 Penya & Friends
    

app/views/layouts/flatly.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "pree_board"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "flatly", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"} pree-board
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Home", "/"
            %li
              %a{href: "#"}
                Log
                / = current_user ? "out, " + current_user.last_name.capitalize : "in"

    .container
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert

      = yield

      .container
        .row
          .col-md-4.col-md-offset-4
            .panel.panel-default
              .panel-heading
                %h3.panel-title Please sign in
              .panel-body
                %form{"accept-charset" => "UTF-8", :role => "form"}
                  %fieldset
                    .form-group
                      %input.form-control{:name => "email", :placeholder => "E-mail", :type => "text"}/
                    .form-group
                      %input.form-control{:name => "password", :placeholder => "Password", :type => "password", :value => ""}/
                    .checkbox
                      %label
                        %input{:name => "remember", :type => "checkbox", :value => "Remember Me"}/
                        Remember Me
                    %input.btn.btn-lg.btn-primary.btn-block{:type => "submit", :value => "Login"}/

    .footer
      .container
        %p.text-muted
          Copyright ©2014 penyah
    

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "flatly"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/welcome/index.html.haml
/ END NAV SECTION
/ HEADER SECTION

#header-section.jumbotron
  .container
    .message-box.clearfix
      .left-col.flexslider.home-slider
        %ul.slides
          %li
            %p LICENSURE
          %li
            %p BOARD
          %li
            %p ENTRANCE
      .right-col
        %p
          EXAMS
          %br
          Made
          %span EASY

/ #header-section
/   .container
/     .row.main-top-margin
/       .col-md-6.col-md-offset-3
/         .text-center
/           %i.fa.fa-briefcase.main-icon
/           %br/
/     .row.main-low-margin
/       .col-md-12
/         .text-center
/           %h2.head-line ...
/ END HEADER SECTION
/ / ABOUT SECTION
/ #about-section.section
/   .container
/     .row.main-low-margin
/       .col-md-10.col-md-offset-1.col-sm-10.col-sm-offset-1
/         %h1 Our Profile
/         %h5
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/ .container
/   .row.main-low-margin.text-center
/     .col-md-4.col-sm-4
/       %i.fa.fa-flask.fa-5x.color-brown
/       %h3 TESTED DESIGN
/       %p
/         Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/     .col-md-4.col-sm-4
/       %i.fa.fa-pencil.fa-5x.color-blue
/       %h3 EASY TO CUSTOMIZE
/       %p
/         Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/     .col-md-4.col-sm-4
/       %i.fa.fa-thumbs-up.fa-5x.color-black
/       %h3 WELL DOCUMENTED
/       %p
/         Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/ .space-bottom
/ / END ABOUT SECTION
/ / PARALLAX SECTION ONE
/ %section#story-freext
/   %article
/     %h3
/       %i.fa.fa-flask
/       Lorem ipsum dolor sit amet
/     %span
/       Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/       %br/
/       Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/   .parallax{"data-velocity" => "-.3"}
/ / END PARALLAX SECTION ONE
/ / PRICE SECTION
/ #price-section.section
/   .container
/     .row.main-low-margin
/       .col-md-10.col-md-offset-1.col-sm-10.col-sm-offset-1
/         %h1 Pricing Details
/         %h5
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/           Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
/ #pricing-section.container
/   .main-low-margin.col-md-10.col-md-offset-1.col-sm-10.col-sm-offset-1.margin-top-100
/     #pricing-table.row
/       .col-md-4.col-sm-4
/         %ul.plan-main
/           %li.plan-name Starter
/           %li.plan-price $ 100
/           %li 5GB Storage
/           %li 1GB Space
/           %li 200 Bandwidth
/           %li 100 Email Address
/           %li 24x7 Support
/           %li Live Chat
/           %li.plan-action
/             %a.btn.btn-primary.btn-lg{:href => "#"} Signup
/       .col-md-4.col-sm-4
/         %ul.plan-main.featured.active
/           %li.plan-name Medium
/           %li.plan-price $ 200
/           %li 5GB Storage
/           %li 1GB Space
/           %li 200 Bandwidth
/           %li 100 Email Address
/           %li 24x7 Support
/           %li Live Chat
/           %li.plan-action
/             %a.btn.btn-primary.btn-lg{:href => "#"} Signup
/       .col-md-4.col-sm-4
/         %ul.plan-main
/           %li.plan-name Advance
/           %li.plan-price $ 300
/           %li 5GB Storage
/           %li 1GB Space
/           %li 200 Bandwidth
/           %li 100 Email Address
/           %li 24x7 Support
/           %li Live Chat
/           %li.plan-action
/             %a.btn.btn-primary.btn-lg{:href => "#"} Signup
/   / ./ Row Content
/ .space-bottom
/ / END PRICE SECTION
/ / PARALLAX SECTION TWO
/ %section#story-two
/   %article
/     %h3
/       %i.fa.fa-desktop
/       Lorem ipsum dolor sit amet
/     %span
/       Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/       %br/
/       Lorem ipsum dolor sit amet, consectetur adipiscing elit.
/   .parallax{"data-velocity" => "-.1"}
/   .parallax{"data-fit" => "125", "data-velocity" => "-.5"}
/ END PARALLAX SECTION TWO
/ CONTACT SECTION
#contact-section.section
  .container#contact
    %center
      %h1 Your licensure exam buddy.

    .row.main-low-margin
      .col-md-6.col-md-offset-3
        = form_for Subscriber.new, url: subscribers_path, :method => :post, :role => "form" do |f|
          .input-group    
            = f.email_field :email, :autofocus => true, :placeholder => "Enter your email address", :class => "form-control input-lg", :required => true
            %span.input-group-btn
              = f.submit "Sign Up", :class => "btn btn-primary btn-lg"
        %p
          We're launching soon. Sign up to be the first to know!